
const $=id=>document.getElementById(id);
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(v=>v[1]);
let currentQuestions=[],currentStage="screening",lastResult=null;
let classResults=JSON.parse(localStorage.getItem("qazaqread_class_results")||"[]");
function navActive(){const p=location.pathname.split("/").pop()||"index.html";document.querySelectorAll(".menu a").forEach(a=>{if(a.getAttribute("href")===p)a.classList.add("active")})}
function levelByPercent(p){if(p<50)return{level:"beginner",label:"Бастапқы деңгей",risk:"Қызыл аймақ",zone:"red"};if(p<75)return{level:"middle",label:"Орта деңгей",risk:"Сары аймақ",zone:"yellow"};if(p<90)return{level:"high",label:"Жоғары деңгей",risk:"Жасыл аймақ",zone:"green"};return{level:"advanced",label:"Кеңейтілген деңгей",risk:"Көк аймақ",zone:"blue"}}
function zoneByPercent(p){if(p<50)return{zone:"red",label:"Қызыл",level:"Бастапқы"};if(p<75)return{zone:"yellow",label:"Сары",level:"Орта"};if(p<90)return{zone:"green",label:"Жасыл",level:"Жоғары"};return{zone:"blue",label:"Көк",level:"Жоғары+"}}
function buildDiagnostic(mode="screening"){currentStage=mode;let pool=[];PASSAGES.forEach(p=>p.questions.forEach(q=>pool.push({...q,passageTitle:p.title,passageText:p.text})));let count=mode==="deep"?14:10;currentQuestions=shuffle(pool).slice(0,count);renderTest()}
function buildBalancedDiagnostic(){currentStage="balanced";currentQuestions=[];Object.keys(SKILL_NAMES).forEach(skill=>{let skillPool=[];PASSAGES.forEach(p=>p.questions.filter(q=>q.skill===skill).forEach(q=>skillPool.push({...q,passageTitle:p.title,passageText:p.text})));currentQuestions.push(...shuffle(skillPool).slice(0,2));});currentQuestions=shuffle(currentQuestions);renderTest()}
function renderTest(){if(!$("passageBox"))return;let grouped={};currentQuestions.forEach(q=>grouped[q.passageTitle]=q.passageText);$("passageBox").innerHTML=Object.entries(grouped).map(([t,tx])=>`<h3>${t}</h3><p>${tx}</p>`).join("<hr>");$("questionsBox").innerHTML=currentQuestions.map((q,i)=>`<div class="question"><b>${i+1}. ${q.q}</b>${q.options.map((op,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"> ${op}</label>`).join("")}</div>`).join("");if($("testInfo"))$("testInfo").value=`${currentQuestions.length} сұрақ • ${currentStage==="deep"?"терең диагностика":currentStage==="balanced"?"дағдылар бойынша толық тексеру":"бастапқы скрининг"}`}
function evaluate(){let correct=0,bySkill={},missed=[];currentQuestions.forEach((q,i)=>{let ch=document.querySelector(`input[name="q${i}"]:checked`),ok=ch&&+ch.value===q.answer;if(ok)correct++;if(!bySkill[q.skill])bySkill[q.skill]={total:0,wrong:0};bySkill[q.skill].total++;if(!ok){bySkill[q.skill].wrong++;missed.push(q)}});let percent=Math.round(correct/currentQuestions.length*100),lvl=levelByPercent(percent),weakSkills=Object.entries(bySkill).filter(([s,v])=>v.wrong>0).sort((a,b)=>b[1].wrong-a[1].wrong).map(([s])=>s);lastResult={correct,total:currentQuestions.length,percent,...lvl,weakSkills,mainWeak:weakSkills[0]||"main_idea",missed,date:new Date().toLocaleDateString("kk-KZ")};localStorage.setItem("qazaqread_last_profile",JSON.stringify(lastResult));saveResultToMonitor(lastResult);updateProfile(lastResult);scrollTo({top:0,behavior:"smooth"})}
function getSkillSummary(r){return r.weakSkills&&r.weakSkills.length?r.weakSkills.map(s=>SKILL_NAMES[s]).join(", "):"айқын әлсіз дағды анықталған жоқ"}
function advice(s){return{main_idea:"мәтінді оқығаннан кейін негізгі ойды бір сөйлеммен айту",info:"кім, не, қашан, қайда сұрақтарымен нақты ақпаратты табу",keywords:"мәтіндегі 3–5 тірек сөзді белгілеу",cause:"себеп пен салдарды “неге?” сұрағы арқылы талдау",interpretation:"астарлы ойды өз сөзімен түсіндіру",author:"автор көзқарасын дәлел сөйлем арқылы табу",argument:"пікір — дәлел — қорытынды үлгісімен жауап жазу"}[s]||"мәтінді түсініп оқу"}
function buildParentMessage(name,level){if(!lastResult)return"Диагностикадан кейін нақты хабарлама шығады.";let tone=lastResult.level==="beginner"?"жүйелі қолдау қажет.":lastResult.level==="middle"?"кейбір дағдыларды бекіту қажет.":"нәтиже жақсы, күрделірек мәтіндер ұсынылады.";return`Құрметті ата-ана! ${name} оқу сауаттылығы бойынша диагностикадан өтті. Жалпы нәтижесі: ${lastResult.percent}%. Деңгейі: ${level}. Балаңызға ${tone} Негізгі назар аударатын дағды: ${getSkillSummary(lastResult)}. Үй жағдайында ${advice(lastResult.mainWeak)} ұсынылады. Оқушыға жеке қолдау тапсырмалары берілді, кейін қайта диагностика өткізіледі.`}
function saveResultToMonitor(r){let name=$("studentName")?$("studentName").value.trim()||"Оқушы":"Оқушы",grade=$("studentGrade")?$("studentGrade").value:"7-сынып",idx=classResults.findIndex(x=>x.name===name&&x.grade===grade);let old=idx>=0?classResults[idx]:null;let dynamic=old&&typeof old.screening==="number"?`+${Math.max(0,r.percent-old.screening)}%`:"басталды";let item={name,grade,date:r.date,screening:r.percent,deep:currentStage==="deep"?r.percent:"—",skill:r.mainWeak,zone:r.zone,zoneLabel:r.risk.replace(" аймақ",""),level:r.label.replace(" деңгей",""),dynamic};if(idx>=0)classResults[idx]=item;else classResults.unshift(item);localStorage.setItem("qazaqread_class_results",JSON.stringify(classResults))}
function updateProfile(r){if(!$("scoreBox"))return;let name=$("studentName").value.trim()||"Оқушы";$("scoreBox").textContent=r.percent+"%";$("levelBox").innerHTML=`<span class="level-pill level-${r.zone}">${r.label} • ${r.risk}</span>`;$("weakSkills").innerHTML=r.weakSkills.length?r.weakSkills.map(s=>`<span class="skill">${SKILL_NAMES[s]}</span>`).join(""):`<span class="skill">Негізгі қате анықталмады</span>`;$("routeBox").innerHTML=buildRoute(r);$("parentText").textContent=buildParentMessage(name,r.label);recommendedTasks(r.mainWeak,r.level)}
function buildRoute(r){let sk=SKILL_NAMES[r.mainWeak];return[`1-кезең: ${sk} бойынша қысқа түсіндіру және үлгі талдау.`,`2-кезең: жеңіл тапсырма — мәтіннен жауап табу.`,`3-кезең: бекіту — өз сөзімен түсіндіру.`,`4-кезең: күрделендіру — дәлел қосу.`,`5-кезең: бақылау тапсырмасы.`,`6-кезең: қайта диагностика және динамиканы салыстыру.`].map((t,i)=>`<div class="route-step"><span>${i+1}</span><div>${t}</div></div>`).join("")}
function taskHtml(t,button=false){return`<div class="task-card"><div class="meta"><span class="tag">${SKILL_NAMES[t.skill]}</span><span class="tag">${t.level==="beginner"?"Бастапқы":t.level==="middle"?"Орта":"Жоғары"}</span></div><b>${t.title}</b><p>${t.task}</p><small><b>Мақсат:</b> ${t.goal}</small><br><small><b>Тексеру:</b> ${t.check}</small>${button?`<br><br><button class="btn green" onclick="completeTask()">Орындалды деп белгілеу</button>`:""}</div>`}
function recommendedTasks(skill,level){if(!$("recommendedTasks"))return;let p=TASK_BANK.filter(t=>t.skill===skill&&t.level===level);if(p.length<4)p=TASK_BANK.filter(t=>t.skill===skill);$("recommendedTasks").innerHTML=shuffle(p).slice(0,4).map(t=>taskHtml(t)).join("")}
function loadSupportPlan(){if(!$("supportPlan"))return;let profile=JSON.parse(localStorage.getItem("qazaqread_last_profile")||"null");if(!profile){$("supportPlan").innerHTML="<div class='note'>Алдымен диагностикадан өтіңіз. Сонда бұл бетте оқушыға нақты жеке қолдау жоспары шығады.</div>";return}let pool=TASK_BANK.filter(t=>t.skill===profile.mainWeak&&t.level===profile.level);if(pool.length<6)pool=TASK_BANK.filter(t=>t.skill===profile.mainWeak);let tasks=shuffle(pool).slice(0,6);$("supportTitle").textContent=`Жеке қолдау: ${SKILL_NAMES[profile.mainWeak]}`;$("supportSub").textContent=`Соңғы нәтиже: ${profile.percent}% • ${profile.label} • мақсат: келесі тексеруде нәтижені көтеру`;$("supportPlan").innerHTML=tasks.map((t,i)=>`<div class="route-step"><span>${i+1}</span><div>${taskHtml(t,true)}</div></div>`).join("");updateProgress()}
function completeTask(){let done=+(localStorage.getItem("qazaqread_done")||0);done=Math.min(done+1,6);localStorage.setItem("qazaqread_done",done);updateProgress();alert("Белгіленді. Оқушы келесі кезеңге өтті.")}
function updateProgress(){if(!$("progressBar"))return;let done=+(localStorage.getItem("qazaqread_done")||0);$("progressText").textContent=`Орындалған кезең: ${done}/6`;$("progressBar").style.width=(done/6*100)+"%"}
function selectTask(){if(!$("manualTask"))return;let lvl=$("taskLevel").value,skill=$("taskSkill").value,p=TASK_BANK.filter(t=>(lvl==="all"||t.level===lvl)&&(skill==="all"||t.skill===skill));$("manualTask").innerHTML=taskHtml(pick(p.length?p:TASK_BANK))}
function makeSampleClass(){const names=["Нұрсұлтан","Алихан","Мейіржан","Санжар","Жанель","Ерасыл","Медина","Іңкәр","Данияр","Аяулым"];classResults=names.map((name,i)=>{let sc=[55,49,69,79,33,41,31,30,25,50][i],z=zoneByPercent(sc);return{name,grade:"7-сынып",date:new Date().toLocaleDateString("kk-KZ"),screening:sc,deep:Math.min(100,sc+6+i%5),skill:Object.keys(SKILL_NAMES)[i%7],zone:z.zone,zoneLabel:z.label,level:z.level,dynamic:`+${6+i%7}%`}});localStorage.setItem("qazaqread_class_results",JSON.stringify(classResults));renderClass()}
function renderClass(){if(!$("classTable"))return;if(!classResults.length)$("classTable").innerHTML=`<tr><td colspan="8">Әзірге нәтиже жоқ. Диагностикадан өткен оқушылар осы жерде автоматты түрде пайда болады.</td></tr>`;else $("classTable").innerHTML=classResults.map(s=>`<tr><td><b>${s.name}</b><br><small>${s.grade}</small></td><td>${s.date||"—"}</td><td>${s.screening}${typeof s.screening==="number"?"%":""}</td><td>${s.deep}${typeof s.deep==="number"?"%":""}</td><td>${SKILL_NAMES[s.skill]}</td><td>${s.level}</td><td><span class="level-pill level-${s.zone}">${s.zoneLabel}</span></td><td><b>${s.dynamic}</b></td></tr>`).join("");let c={red:0,yellow:0,green:0,blue:0};classResults.forEach(s=>c[s.zone]++);["red","yellow","green","blue"].forEach(k=>{if($("count_"+k))$("count_"+k).textContent=c[k]})}
function clearClass(){classResults=[];localStorage.removeItem("qazaqread_class_results");renderClass()}
function copyParent(){navigator.clipboard.writeText($("parentText").textContent);alert("Хабарлама көшірілді")}
document.addEventListener("DOMContentLoaded",()=>{navActive();if($("questionsBox"))buildDiagnostic("screening");if($("manualTask"))selectTask();if($("supportPlan"))loadSupportPlan();if($("classTable"))renderClass()});
